phpbb.titania.index:
    path: /
    defaults: { _controller: phpbb.titania.controller.index:display_index, branch: '' }

phpbb.titania.index.branch:
    path: /{branch}
    defaults: { _controller: phpbb.titania.controller.index:display_index, branch: '' }
    requirements:
        branch: \d\.\d|

phpbb.titania.faq:
    path: /faq
    defaults: { _controller: phpbb.titania.controller.faq:handle }

phpbb.titania.queue_stats:
    path: /queue-stats/{contrib_type}
    defaults: { _controller: phpbb.titania.controller.queue_stats:display_stats }

phpbb.titania.support:
    path: /support/{type}
    defaults: { _controller: phpbb.titania.controller.support:display_topics, type: all }

phpbb.titania.author:
    path: /author/{author}/{page}
    defaults: { _controller: phpbb.titania.controller.author:base, page: details }
    requirements:
        page: '|details|contributions|support|discussion|manage|create'

phpbb.titania.download:
    path: /download/{id}/{type}
    defaults: { _controller: phpbb.titania.controller.download:file, id: 0, type: manual }
    requirements:
        id: \d+

phpbb.titania.search:
    path: /search
    defaults: { _controller: phpbb.titania.controller.search:general }

phpbb.titania.search.results:
    path: /search/results
    defaults: { _controller: phpbb.titania.controller.search:general_results }

phpbb.titania.search.contributions:
    path: /find-contribution
    defaults: { _controller: phpbb.titania.controller.search:contributions }

phpbb.titania.search.contributions.results:
    path: /find-contribution/results
    defaults: { _controller: phpbb.titania.controller.search:contribution_results }

phpbb.titania.colorizeit:
    path: /colorizeit/{id}
    defaults: { _controller: phpbb.titania.controller.colorizeit:colorizeit_data }
    requirements:
        id: \d+

phpbb.titania.contribution.id:
    path: /contribution/id/{id}/
    defaults: { _controller: phpbb.titania.controller.contrib:redirect_from_id }
    requirements:
        id: \d+

phpbb.titania.composer:
    path: /composer/{filename}.json
    defaults: { _controller: phpbb.titania.controller.composer:serve_file }

phpbb.titania.category:
    path: /{category1}/{category2}/{category3}/{category4}
    defaults: { _controller: phpbb.titania.controller.index:display_category, category2: '', category3: '', category4: '' }

phpbb.titania.legacy:
    path: /{path}
    defaults: { _controller: phpbb.titania.controller.legacy_rerouter:redirect }
    requirements:
        path: .*

