services:
    phpbb.titania.controller.index:
        class: phpbb\titania\controller\index
        arguments:
            - @auth
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.cache
            - @path_helper
            - @phpbb.titania.tracking

    phpbb.titania.controller.faq:
        class: phpbb\titania\controller\faq
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @phpbb.titania.display

    phpbb.titania.controller.queue_stats:
        class: phpbb\titania\controller\queue_stats
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.queue.stats

    phpbb.titania.controller.support:
        class: phpbb\titania\controller\support
        arguments:       
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.tracking

    phpbb.titania.controller.all_contribs:
        class: phpbb\titania\controller\all_contribs
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.tracking
            - @path_helper

    phpbb.titania.controller.author:
        class: phpbb\titania\controller\author
        scope: prototype
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.config
            - @phpbb.titania.cache
            - @phpbb.titania.access
            - @phpbb.titania.tracking
            - @phpbb.titania.message

    phpbb.titania.controller.download:
        class: phpbb\titania\controller\download
        arguments:
            - @dbal.conn
            - @auth
            - @user
            - @request
            - @phpbb.titania.controller.helper
            - @phpbb.titania.config
            - @phpbb.titania.access
            - %core.root_path%
            - %core.php_ext%

    phpbb.titania.controller.search:
        class: phpbb\titania\controller\search
        scope: prototype
        arguments:
            - @config
            - @template
            - @user
            - @phpbb.titania.cache
            - @request
            - @phpbb.titania.controller.helper
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.sort

    phpbb.titania.controller.colorizeit:
        class: phpbb\titania\controller\colorizeit
        arguments:
            - @dbal.conn
            - @user
            - @request
            - @phpbb.titania.controller.helper
            - @phpbb.titania.config

    phpbb.titania.controller.legacy_rerouter:
        class: phpbb\titania\controller\legacy_rerouter
        arguments:
            - @phpbb.titania.controller.helper

    phpbb.titania.controller.contrib:
        class: phpbb\titania\controller\contribution\contribution
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.access
            - @phpbb.titania.tracking
            - @phpbb.titania.subscriptions

    phpbb.titania.controller.contrib.support:
        class: phpbb\titania\controller\contribution\support
        scope: prototype
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.access
            - @phpbb.titania.tracking
            - @phpbb.titania.subscriptions
            - @phpbb.titania.posting

    phpbb.titania.controller.contrib.faq:
        class: phpbb\titania\controller\contribution\faq
        scope: prototype
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.access
            - @phpbb.titania.tracking
            - @phpbb.titania.sort
            - @phpbb.titania.attachment.operator
            - @phpbb.titania.message

    phpbb.titania.controller.contrib.manage:
        class: phpbb\titania\controller\contribution\manage
        scope: prototype
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.access
            - @phpbb.titania.message
            - @phpbb.titania.attachment.uploader
            - @phpbb.titania.attachment.uploader

    phpbb.titania.controller.contrib.revision:
        class: phpbb\titania\controller\contribution\revision
        scope: prototype
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.access
            - @phpbb.titania.attachment.uploader
            - @phpbb.titania.subscriptions
            - @phpbb.titania.message

    phpbb.titania.controller.contrib.revision.edit:
        class: phpbb\titania\controller\contribution\revision_edit
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.access

    phpbb.titania.controller.manage:
        class: phpbb\titania\controller\manage\manage
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.manage.queue:
        class: phpbb\titania\controller\manage\queue\queue
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.subscriptions

    phpbb.titania.controller.manage.queue.item:
        class: phpbb\titania\controller\manage\queue\item
        scope: prototype
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.tags
            - @phpbb.titania.message
            - @phpbb.titania.posting

    phpbb.titania.controller.manage.queue.tools:
        class: phpbb\titania\controller\manage\queue\tools
        arguments:
            - @user
            - @template
            - @request
            - @phpbb.titania.controller.helper
            - @phpbb.titania.config

    phpbb.titania.controller.manage.attention:
        class: phpbb\titania\controller\manage\attention
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.subscriptions

    phpbb.titania.controller.manage.categories:
        class: phpbb\titania\controller\manage\categories
        scope: prototype
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.message
            - @phpbb.titania.sync

    phpbb.titania.controller.manage.queue_discussion:
        class: phpbb\titania\controller\manage\queue_discussion
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.tracking

    phpbb.titania.controller.manage.administration:
        class: phpbb\titania\controller\manage\administration
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.ucp.subscriptions:
        class: phpbb\titania\controller\ucp\subscriptions
        scope: prototype
        arguments:
            - @dbal.conn
            - @template
            - @user
            - @request
            - @phpbb.titania.controller.helper
            - @phpbb.titania.config
            - @phpbb.titania.display
            - @phpbb.titania.tracking
            - @phpbb.titania.sort
