imports:
    - { resource: controllers.yml }
    - { resource: cron.yml }
    - { resource: parameters.yml }

services:
    phpbb.titania.access:
        class: phpbb\titania\access
        arguments:
            - @dbal.conn
            - @user
            - @phpbb.titania.config

    phpbb.titania.attachment:
        class: phpbb\titania\attachment\attachment
        scope: prototype
        arguments:
            - @dbal.conn
            - @config
            - @user
            - @phpbb.titania.config
            - @phpbb.titania.controller.helper

    phpbb.titania.attachment.operator:
        class: phpbb\titania\attachment\operator
        scope: prototype
        arguments:
            - @dbal.conn
            - @config
            - @user
            - @template
            - @phpbb.titania.attachment

    phpbb.titania.attachment.plupload:
        class: phpbb\titania\attachment\plupload
        arguments:
             - %core.root_path%
             - @config
             - @request
             - @user
             - @php_ini
             - @mimetype.guesser

    phpbb.titania.attachment.uploader:
        class: phpbb\titania\attachment\uploader
        scope: prototype
        arguments:
            - @phpbb.titania.attachment.operator
            - @user
            - @config
            - @request
            - @template
            - @path_helper
            - @controller.helper
            - @phpbb.titania.config
            - @mimetype.guesser
            - @phpbb.titania.attachment.plupload
            - @phpbb.titania.access
            - %core.root_path%
            - %core.php_ext%

    phpbb.titania.bbcode.demo:
        class: phpbb\titania\contribution\bbcode\demo\demo
        arguments:
            - @phpbb.titania.cache
            - %core.root_path%
            - %core.php_ext%

    phpbb.titania.config:
        class: phpbb\titania\config\config
        arguments:
            - @config
            - %phpbb.titania.root_path%
            - %core.php_ext%

    phpbb.titania.contribution.prevalidator_helper:
        class: phpbb\titania\contribution\prevalidator_helper
        arguments:
            - @user
            - %phpbb.titania.root_path%

    phpbb.titania.controller.helper:
        class: phpbb\titania\controller\helper
        arguments:
            - @template
            - @user
            - @config
            - @controller.provider
            - @ext.manager
            - @symfony_request
            - @request
            - @filesystem
            - %core.root_path%
            - %core.php_ext%

    phpbb.titania.cache:
        class: phpbb\titania\cache\service
        arguments:
             - @cache.driver
             - @config
             - @dbal.conn
             - %core.root_path%
             - %core.php_ext%

    phpbb.titania.display:
        class: phpbb\titania\display
        arguments:
             - @auth
             - @config
             - @phpbb.titania.cache
             - @template
             - @user
             - @phpbb.titania.controller.helper
             - @path_helper

    phpbb.titania.extension.prevalidator:
        class: phpbb\titania\contribution\extension\prevalidator

    phpbb.titania.listener:
        class: phpbb\titania\event\main_listener
        arguments:
            - @user
            - @template
            - @phpbb.titania.controller.helper
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    phpbb.titania.mod.prevalidator:
        class: phpbb\titania\contribution\mod\prevalidator
        arguments:
             - @phpbb.titania.config
             - @user
             - @template
             - @phpbb.titania.contribution.prevalidator_helper
             - %core.root_path%
             - %phpbb.titania.root_path%
             - %core.php_ext%

    phpbb.titania.queue.stats:
        class: phpbb\titania\queue\stats
        arguments:
            - @dbal.conn
            - @user
            - @template

    phpbb.titania.sort:
        class: phpbb\titania\sort
        scope: prototype
        arguments:
            - @dbal.conn
            - @user
            - @template
            - @request
            - @pagination
            - @path_helper

    phpbb.titania.style.demo:
        class: phpbb\titania\contribution\style\demo\demo
        arguments:
            - @dbal.conn
            - @user
            - @template
            - @phpbb.titania.config
            - @phpbb.titania.controller.helper
            - %tables.users%

    phpbb.titania.style.demo.manager:
        class: phpbb\titania\contribution\style\demo\manager
        arguments:
            - @user
            - @service_container
            - @phpbb.titania.config
            - %core.php_ext%

    phpbb.titania.subscriptions:
        class: phpbb\titania\subscriptions
        arguments:
            - @dbal.conn
            - @config
            - @request
            - @template
            - @user
            - @path_helper
            - %tables.users%
            - %core.root_path%
            - %core.php_ext%


    phpbb.titania.tags:
        class: phpbb\titania\tags
        arguments:
            - @user
            - @phpbb.titania.cache

    phpbb.titania.tracking:
         class: phpbb\titania\tracking
         arguments:
             - @dbal.conn
             - @user
             - @request
             - @config

    phpbb.titania.translation.prevalidator:
         class: phpbb\titania\contribution\translation\prevalidator
         arguments:
             - @user
             - @phpbb.titania.contribution.prevalidator_helper
